### ISSUE TITLE
Livewire wire:navigate in link causes window.Mingle undefined error.

### ISSUE THREAD

**Issue by doriandevelops** [ijpatricio/minglejs-demo#2]
I just came across this issue as I was building a new Laravel 11 project with Breeze TALL setup. While using the Livewire navigation component that was provided with the project starter.

I found that when I navigated to the page where my mingle React component was for the very first time on after initial load from anywhere within my app using the `navigation.blade.php` with the `<x-nav-link :href="route('map')" :active="request()->routeIs('map')" wire:navigate>` I would get a `Uncaught TypeError: can't access property "Elements", window.Mingle is undefined` from `mingle.js` and `mingle.blade.php`.

I'm new to Laravel and Livewire and I was unaware of the `wire:navigate` functionality and what it was doing. This is provided in the default starter so just in case other people might come across this issue I wanted to document it. 

I tried to fix it for a while and after debugging for longer than I care to admit I realized it wasn't really a Mingle problem but a problem with how `wire:navigate` tries to fetch the page in the background to give a SPA like UX https://livewire.laravel.com/docs/navigate

Hope this is helpful!

**Comment by ijpatricio** [comment]
Hey @doriandevelops !

Hope you're enjoying, overall! Using the $wire to perform server side methods for me, almost feels like cheating 😄 

That's right! I didn't take `wire:navigate` into consideration. Hmmm not 100% sure, but I think it's possible to make Mingle compatible with it. I'll have a look this week.

Also, can I have your thoughts on how hard it was to setup Mingle?

This is hard to have as a package, because it means to change project files, and it is risky to do so in existing projects.
As it stands today, is more of a demo/boilerplate, but it gets outdated as time passes.

I'm not sure of the next step. It could be one of these:
1. Make a package, and a set of instructions, for manual steps after install.
2. Make it a starter kit. Something to run right after Breeze/Jetstream. But only then, not later.

The 1st makes it possible with any project, while the 2nd one is more seamless but only works for new projects.

Any thoughts?

**Comment by doriandevelops** [comment]
Hey @ijpatricio,

Thanks for building this tool!

I'm totally new to Laravel and Livewire so I just don't know how some things work. That's why I think the `wire:navigate` thing got me. It wasn't a big deal because for what I'm doing and the component I'm using on the page it's ok to not prefetch the page. If you could get it working that would be awesome though!

For me setting it up was a little difficult because I'm a Laravel rookie and I don't know how a Laravel project is structured. So I went in and basically reverse-engineered what the demo was doing line by line, file by file, with the demo open on one vscode window and my project on the other. 

That was a bit of work because it does feel like it's more of a starter kit atm and I had an existing project, and the readme felt more setup for a starter. I ran into not knowing where to put some of the file declarations and small issues like that. At the end I was pretty much doing a search for "Hello world" because I was using the react component and copying over the functionality to my project folders. I think if I knew Laravel better I wouldn't of had such a hard time tbh it was a skill issue on my end.

As far as how to ship Mingle I think the most straight forward and simple way would be as a starter but considering that people might want to add this to their projects when they need a Vue or React island you might want to document how to do that. 

Maybe keep a separate Mingle demo project that isn't installed as a package but can be added manually to existing projects by following the steps to add all the needed files and references. Basically that's all I had to do to add it to my existing project. so I'm sure other could do that too and having a step by step guide would be nice.

Anyway, thanks again for building this and all your help on Twitter! I also wouldn't mind contributing to this once I get a little better at Laravel and have some free time!

**Comment by ijpatricio** [comment]
Hey @doriandevelops 

Thanks again, for going all in with this!

Exactly, this is a starter as it stands. I was a little paralysed by thinking on implementing ox existing projects, since this means to tinker with existing js files and vite config etc.

Maybe that way, is a good "compromise/middle ground".
Having a package we can install at any point.
If in a new project, just run `php artisan mingle:install`, because the file states is known, I can update them with confidence.
If not, follow "this few steps".
Sounds like a great way!

Iirc, I told you on X that I would tinker with Mingle with `wire:navigate` and I have good news: 99% working 😄 
![image](https://github.com/ijpatricio/minglejs-demo/assets/26031459/912a3fa8-20ba-4b3b-993d-e9ede66c2f20)

There's one last step to go...
MingleJS needs to know when Livewire has finished loading the new scripts loaded via ajax.
Filehere: https://github.com/livewire/livewire/blob/e62eb896f6b03f78c8aade9f85ec61dbe075a7f4/js/plugins/navigate/index.js#L89

Preview:
![image](https://github.com/ijpatricio/minglejs-demo/assets/26031459/a89bd621-bf36-417d-b124-51cb268795be)

If I can get a PR emitting an event here... Then I can finalize my code to make wire:navigate compatible.

Let's see what they have to say!

**Comment by ijpatricio** [comment]
@doriandevelops , better news, I won't need the PR, it seems....

I'll rely on Alpine to know when, it's working... I'll have to wrap up all this tinkering, and might end up simplifying the codebase 👍

**Comment by ijpatricio** [comment]
@doriandevelops .... great news! It's now working with `wire:navigate`, and much cleaner.

Sorry, as it isn't still a published package, so the changes must be manual.

If you can wait a little I can publish this as a package...

As you now know where stuff are, maybe you can do it on your own.
The only breaking change is that now the component is anywhere you want.

In the LW component, now the path is from root, just like in `vite-config.js`

    public function component(): string
    {
        return 'resources/js/mingles/HelloWorld/index.jsx';
    }

**Comment by ijpatricio** [comment]
Also, added in the Docs, the link to open an online environment with GitPod. 
Just go to the link: https://gitpod.io/#https://github.com/ijpatricio/minglejs-demo
There's a generous free tier, it surely is enough to try some stuff here and then.

**Comment by doriandevelops** [comment]
Hey @ijpatricio this is awesome! I'm a bit busy today as we're getting ready for a flight tomorrow but I will try to test this out on my project as soon as I get some time and I will let you know how everything works out. Thanks for the updates!

**Comment by ijpatricio** [comment]
Hey Dorian,

I forgot to close this. 😄 

By now, there's the package released, and I hope you can try it and let me know if there's anything you see fit to improve! 

Thanks a bunch for all the support!
