### ISSUE TITLE
do you plan to auto binding variable in livewire with vue variable.

### ISSUE THREAD

**Issue by irvine48** [ijpatricio/minglejs-demo#6]
first of all thank for your work, looking forward for the release,

do you plan to auto binding variable in liveware to vue? actually looking forward from splade which quite similar function [laravel-splade](https://github.com/protonemedia/laravel-splade).

```
<?php

namespace App\Livewire;

use Ijpatricio\Mingle\Concerns\InteractsWithMingles;
use Ijpatricio\Mingle\Contracts\HasMingles;
use Livewire\Component;

class VueCounter extends Component implements HasMingles
{
    use InteractsWithMingles;

    public $amount = null;  <----- like this will automatic update value and unable in frontend.

    public function component(): string
    {
        return 'resources/js/vue-counter/index.js';
    }

    public function mingleData()
    {
        return [
            'message' => 'Message in a bottle 🍾',
        ];
    }

    public function doubleIt()
    {
        $this->amount *= 2; <----- like this will automatic update value and unable in frontend.
    }
}
```

**Comment by ijpatricio** [comment]
Hey Irvine,

Thanks for your kind comments, and initiative to improve the tool!

The fact is, it's quite simple to provide data to the backend

PHP
```php
public function multiplyInServer(int $amount, int $multiplyBy)
{
    return $amount * $multiplyBy
}
```

JS
```js
const foo = 3
const bar = 5

const res = await wire.multiplyInServer(foo, bar)
```

And are you aware you can achieve binding already, with `$wire.$watch`, and `$wire.$set`?

You just have to do that manually in Vue/Reac, with a listener, and setting the new value on change (computed setter, I think).

Doing that automatically, could become problematic, IMO, because for a `.live` attribute, it may starts making ajax requests without the developer noticing (computed, useEffect), and more qwirks of the kind...
But I do understand your desire, because I have it as well. It's just that, as a default, it may not be favourable to every scenario.

I do want to take some action to improve even further the DX, regarding state.
- maybe hooking into Livewire's `@entangle`, and achieve want you describe, but explicitly - you have to write it, not auto
- maybe having a helper that would set a Store (Pinia/Zustand, for Vue/React)

These are just thoughts for now, and not actively building it - for now.
Waiting for more feedback, and that would come on the 1.0 release, yeah
